# Collecting data

In [13]:
## Importing libraries
import yfinance as yf
import pandas as pd

## Fundamental analysis

In [3]:
microsoft = yf.Ticker('MSFT')

### Microsoft's income statement in a DataFrame

In [5]:
microsoft.income_stmt

,2025-06-30,2024-06-30,2023-06-30,2022-06-30
Tax Effect Of Unusual Items,-7.708800e+07,-9.991800e+07,-2.850000e+06,4.375400e+07
Tax Rate For Calcs,1.760000e-01,1.820000e-01,1.900000e-01,1.310000e-01
Normalized EBITDA,1.606030e+11,1.335580e+11,1.051550e+11,9.990500e+10
Total Unusual Items,-4.380000e+08,-5.490000e+08,-1.500000e+07,3.340000e+08
Total Unusual Items Excluding Goodwill,-4.380000e+08,-5.490000e+08,-1.500000e+07,3.340000e+08
Net Income From Continuing Operation Net Minority Interest,1.018320e+11,8.813600e+10,7.236100e+10,7.273800e+10
Reconciled Depreciation,3.415300e+10,2.228700e+10,1.386100e+10,1.446000e+10
Reconciled Cost Of Revenue,8.783100e+10,7.411400e+10,6.586300e+10,6.265000e+10
EBITDA,1.601650e+11,1.330090e+11,1.051400e+11,1.002390e+11
EBIT,1.260120e+11,1.107220e+11,9.127900e+10,8.577900e+10
Net Interest Income,2.620000e+08,2.220000e+08,1.026000e+09,3.100000e+07
Interest Expense,2.385000e+09,2.935000e+09,1.968000e+09,2.063000e+09
Interest Income,2.647000e+09,3.157000e+09,2.994000e+09,2.094000e+09
Normalized Income,1.021929e+11,8.858508e+10,7.237315e+10,7.244775e+10
Net Income From Continuing And Discontinued Operation,1.018320e+11,8.813600e+10,7.236100e+10,7.273800e+10
Total Expenses,1.531960e+11,1.356890e+11,1.233920e+11,1.148870e+11
Total Operating Income As Reported,1.285280e+11,1.094330e+11,8.852300e+10,8.338300e+10
Diluted Average Shares,7.465000e+09,7.469000e+09,7.472000e+09,7.540000e+09
Basic Average Shares,7.433000e+09,7.431000e+09,7.446000e+09,7.496000e+09
Diluted EPS,1.364000e+01,1.180000e+01,9.680000e+00,9.650000e+00
Basic EPS,1.370000e+01,1.186000e+01,9.720000e+00,9.700000e+00
Diluted NI Availto Com Stockholders,1.018320e+11,8.813600e+10,7.236100e+10,7.273800e+10
Net Income Common Stockholders,1.018320e+11,8.813600e+10,7.236100e+10,7.273800e+10
Net Income,1.018320e+11,8.813600e+10,7.236100e+10,7.273800e+10
Net Income Including Noncontrolling Interests,1.018320e+11,8.813600e+10,7.236100e+10,7.273800e+10
Net Income Continuous Operations,1.018320e+11,8.813600e+10,7.236100e+10,7.273800e+10
Tax Provision,2.179500e+10,1.965100e+10,1.695000e+10,1.097800e+10
Pretax Income,1.236270e+11,1.077870e+11,8.931100e+10,8.371600e+10
Other Income Expense,-5.163000e+09,-1.868000e+09,-2.380000e+08,3.020000e+08
Other Non Operating Income Expenses,-4.725000e+09,-1.319000e+09,-2.230000e+08,-3.200000e+07
Special Income Charges,-9.430000e+08,-2.060000e+08,-3.000000e+07,-1.010000e+08
Write Off,9.430000e+08,2.060000e+08,3.000000e+07,1.010000e+08
Gain On Sale Of Security,5.050000e+08,-3.430000e+08,1.500000e+07,4.350000e+08
Net Non Operating Interest Income Expense,2.620000e+08,2.220000e+08,1.026000e+09,3.100000e+07
Interest Expense Non Operating,2.385000e+09,2.935000e+09,1.968000e+09,2.063000e+09
Interest Income Non Operating,2.647000e+09,3.157000e+09,2.994000e+09,2.094000e+09
Operating Income,1.285280e+11,1.094330e+11,8.852300e+10,8.338300e+10
Operating Expense,6.536500e+10,6.157500e+10,5.752900e+10,5.223700e+10
Research And Development,3.248800e+10,2.951000e+10,2.719500e+10,2.451200e+10
Selling General And Administration,3.287700e+10,3.206500e+10,3.033400e+10,2.772500e+10
Selling And Marketing Expense,2.565400e+10,2.445600e+10,2.275900e+10,2.182500e+10
General And Administrative Expense,7.223000e+09,7.609000e+09,7.575000e+09,5.900000e+09
Other Gand A,7.223000e+09,7.609000e+09,7.575000e+09,5.900000e+09
Gross Profit,1.938930e+11,1.710080e+11,1.460520e+11,1.356200e+11
Cost Of Revenue,8.783100e+10,7.411400e+10,6.586300e+10,6.265000e+10
Total Revenue,2.817240e+11,2.451220e+11,2.119150e+11,1.982700e+11
Operating Revenue,2.817240e+11,2.451220e+11,2.119150e+11,1.982700e+11

### Microsoft's balance sheet in a DataFrame

In [6]:
microsoft.balance_sheet

,2025-06-30,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Ordinary Shares Number,7.434159e+09,7.434139e+09,7.432000e+09,7.464000e+09,NaN
Share Issued,7.434159e+09,7.434139e+09,7.432000e+09,7.464000e+09,NaN
Net Debt,1.290900e+10,3.331500e+10,1.253300e+10,3.585000e+10,NaN
Total Debt,6.058800e+10,6.712700e+10,5.996500e+10,6.127000e+10,NaN
Tangible Book Value,2.013660e+11,1.216600e+11,1.289710e+11,8.772000e+10,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,9.455500e+10,7.553100e+10,1.112560e+11,1.047490e+11,NaN
Other Short Term Investments,6.431300e+10,5.721600e+10,7.655200e+10,9.081800e+10,NaN
Cash And Cash Equivalents,3.024200e+10,1.831500e+10,3.470400e+10,1.393100e+10,NaN
Cash Equivalents,1.853100e+10,6.744000e+09,2.622600e+10,5.673000e+09,NaN
Cash Financial,1.171100e+10,1.157100e+10,8.478000e+09,8.258000e+09,NaN

### Microsoft's cash flow in a DataFrame

In [7]:
microsoft.cash_flow

,2025-06-30,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Free Cash Flow,7.161100e+10,7.407100e+10,5.947500e+10,6.514900e+10,NaN
Repurchase Of Capital Stock,-1.842000e+10,-1.725400e+10,-2.224500e+10,-3.269600e+10,NaN
Repayment Of Debt,-3.216000e+09,-2.907000e+10,-2.750000e+09,-9.023000e+09,NaN
Issuance Of Debt,0.000000e+00,2.439500e+10,0.000000e+00,0.000000e+00,NaN
Issuance Of Capital Stock,2.056000e+09,2.002000e+09,1.866000e+09,1.841000e+09,NaN
Capital Expenditure,-6.455100e+10,-4.447700e+10,-2.810700e+10,-2.388600e+10,NaN
End Cash Position,3.024200e+10,1.831500e+10,3.470400e+10,1.393100e+10,NaN
Beginning Cash Position,1.831500e+10,3.470400e+10,1.393100e+10,1.422400e+10,NaN
Effect Of Exchange Rate Changes,6.300000e+07,-2.100000e+08,-1.940000e+08,-1.410000e+08,NaN
Changes In Cash,1.186400e+10,-1.617900e+10,2.096700e+10,-1.520000e+08,NaN
Financing Cash Flow,-5.169900e+10,-3.775700e+10,-4.393500e+10,-5.887600e+10,NaN
Cash Flow From Continuing Financing Activities,-5.169900e+10,-3.775700e+10,-4.393500e+10,-5.887600e+10,NaN
Net Other Financing Charges,-2.291000e+09,-1.309000e+09,-1.006000e+09,-8.630000e+08,NaN
Cash Dividends Paid,-2.408200e+10,-2.177100e+10,-1.980000e+10,-1.813500e+10,NaN
Common Stock Dividend Paid,-2.408200e+10,-2.177100e+10,-1.980000e+10,-1.813500e+10,NaN
Net Common Stock Issuance,-1.636400e+10,-1.525200e+10,-2.037900e+10,-3.085500e+10,NaN
Common Stock Payments,-1.842000e+10,-1.725400e+10,-2.224500e+10,-3.269600e+10,NaN
Common Stock Issuance,2.056000e+09,2.002000e+09,1.866000e+09,1.841000e+09,NaN
Net Issuance Payments Of Debt,-8.962000e+09,5.750000e+08,-2.750000e+09,-9.023000e+09,NaN
Net Short Term Debt Issuance,-5.746000e+09,5.250000e+09,0.000000e+00,0.000000e+00,NaN
Short Term Debt Issuance,NaN,5.250000e+09,0.000000e+00,0.000000e+00,NaN
Net Long Term Debt Issuance,-3.216000e+09,-4.675000e+09,-2.750000e+09,-9.023000e+09,NaN
Long Term Debt Payments,-3.216000e+09,-2.907000e+10,-2.750000e+09,-9.023000e+09,NaN
Long Term Debt Issuance,0.000000e+00,2.439500e+10,0.000000e+00,0.000000e+00,NaN
Investing Cash Flow,-7.259900e+10,-9.697000e+10,-2.268000e+10,-3.031100e+10,NaN
Cash Flow From Continuing Investing Activities,-7.259900e+10,-9.697000e+10,-2.268000e+10,-3.031100e+10,NaN
Net Other Investing Changes,2.317000e+09,-1.298000e+09,-3.116000e+09,-2.825000e+09,NaN
Net Investment Purchase And Sale,-4.387000e+09,1.793700e+10,1.021300e+10,1.843800e+10,NaN
Sale Of Investment,2.538800e+10,3.566900e+10,4.786400e+10,4.489400e+10,NaN
Purchase Of Investment,-2.977500e+10,-1.773200e+10,-3.765100e+10,-2.645600e+10,NaN
Net Business Purchase And Sale,-5.978000e+09,-6.913200e+10,-1.670000e+09,-2.203800e+10,NaN
Purchase Of Business,-5.978000e+09,-6.913200e+10,-1.670000e+09,-2.203800e+10,NaN
Net PPE Purchase And Sale,-6.455100e+10,-4.447700e+10,-2.810700e+10,-2.388600e+10,NaN
Purchase Of PPE,-6.455100e+10,-4.447700e+10,-2.810700e+10,-2.388600e+10,NaN
Operating Cash Flow,1.361620e+11,1.185480e+11,8.758200e+10,8.903500e+10,NaN
Cash Flow From Continuing Operating Activities,1.361620e+11,1.185480e+11,8.758200e+10,8.903500e+10,NaN
Change In Working Capital,-5.350000e+09,1.824000e+09,-2.388000e+09,4.460000e+08,NaN
Change In Other Working Capital,5.400000e+09,7.035000e+09,5.177000e+09,5.805000e+09,NaN
Change In Other Current Liabilities,4.947000e+09,5.616000e+09,2.825000e+09,3.169000e+09,NaN
Change In Other Current Assets,-5.994000e+09,-8.465000e+09,-4.824000e+09,-3.514000e+09,NaN
Change In Payables And Accrued Expense,5.690000e+08,3.545000e+09,-2.721000e+09,2.943000e+09,NaN
Change In Payable,5.690000e+08,3.545000e+09,-2.721000e+09,2.943000e+09,NaN
Change In Account Payable,5.690000e+08,3.545000e+09,-2.721000e+09,2.943000e+09,NaN
Change In Tax Payable,NaN,1.687000e+09,-3.580000e+08,6.960000e+08,-2.309000e+09
Change In Income Tax Payable,NaN,1.687000e+09,-3.580000e+08,6.960000e+08,-2.309000e+09
Change In Inventory,3.090000e+08,1.284000e+09,1.242000e+09,-1.123000e+09,NaN
Change In Receivables,-1.058100e+10,-7.191000e+09,-4.087000e+09,-6.834000e+09,NaN
Changes In Account Receivables,-1.058100e+10,-7.191000e+09,-4.087000e+09,-6.834000e+09,NaN
Stock Based Compensation,1.197400e+10,1.073400e+10,9.611000e+09,7.502000e+09,NaN
Unrealized Gain Loss On Investment Securities,-5.360000e+08,-1.460000e+08,-3.030000e+08,-5.090000e+08,NaN
Asset Impairment Charge,9.430000e+08,2.060000e+08,3.000000e+07,1.010000e+08,NaN
Deferred Tax,-7.056000e+09,-4.738000e+09,-6.059000e+09,-5.702000e+09,NaN
Deferred Income Tax,-7.056000e+09,-4.738000e+09,-6.059000e+09,-5.702000e+09,NaN
Depreciation Amortization Depletion,3.415300e+10,2.228700e+10,1.386100e+10,1.446000e+10,NaN
Depreciation And Amortization,3.415300e+10,2.228700e+10,1.386100e+10,1.446000e+10,NaN
Depreciation,3.415300e+10,2.228700e+10,1.386100e+10,1.446000e+10,NaN
Operating Gains Losses,2.020000e+08,2.450000e+08,4.690000e+08,-1.000000e+06,NaN
Gain Loss On Investment Securities,2.020000e+08,2.450000e+08,4.690000e+08,-1.000000e+06,NaN
Net Income From Continuing Operations,1.018320e+11,8.813600e+10,7.236100e+10,7.273800e+10,NaN

### Access the specific information in financial account statements

In [9]:
microsoft.income_stmt["2024-06-30"]["EBITDA"]

np.float64(133009000000.0)

### Get the quarterly results of the three account statements

In [10]:
microsoft.quarterly_income_stmt

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31
Tax Effect Of Unusual Items,6.520000e+07,1.871500e+08,4.951251e+05,6.966000e+07,-2.032200e+08
Tax Rate For Calcs,2.000000e-01,1.900000e-01,1.650420e-01,1.800000e-01,1.800000e-01
Normalized EBITDA,5.785400e+10,4.707500e+10,4.443100e+10,4.032400e+10,3.675500e+10
Total Unusual Items,3.260000e+08,9.850000e+08,3.000000e+06,3.870000e+08,-1.129000e+09
Total Unusual Items Excluding Goodwill,3.260000e+08,9.850000e+08,3.000000e+06,3.870000e+08,-1.129000e+09
Net Income From Continuing Operation Net Minority Interest,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10,2.410800e+10
Reconciled Depreciation,9.198000e+09,1.306100e+10,1.120300e+10,8.740000e+09,5.667000e+09
Reconciled Cost Of Revenue,2.597800e+10,2.404300e+10,2.401400e+10,2.191900e+10,2.179900e+10
EBITDA,5.818000e+10,4.806000e+10,4.443400e+10,4.071100e+10,3.562600e+10
EBIT,4.898200e+10,3.499900e+10,3.323100e+10,3.197100e+10,2.995900e+10
Net Interest Income,1.040000e+08,2.780000e+08,1.540000e+08,3.000000e+06,6.000000e+06
Interest Expense,7.360000e+08,6.980000e+08,6.150000e+08,5.940000e+08,5.940000e+08
Interest Income,8.400000e+08,9.760000e+08,7.690000e+08,5.970000e+08,6.000000e+08
Normalized Income,3.819720e+10,2.694915e+10,2.723050e+10,2.550666e+10,2.503378e+10
Net Income From Continuing And Discontinued Operation,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10,2.410800e+10
Total Expenses,4.299800e+10,3.971200e+10,4.211800e+10,3.806600e+10,3.797900e+10
Total Operating Income As Reported,3.827500e+10,3.796100e+10,3.432300e+10,3.200000e+10,3.165300e+10
Diluted Average Shares,7.460000e+09,7.466000e+09,7.461000e+09,7.461000e+09,7.468000e+09
Basic Average Shares,7.431000e+09,7.433000e+09,7.432000e+09,7.434000e+09,7.435000e+09
Diluted EPS,5.160000e+00,3.720000e+00,3.650000e+00,3.460000e+00,3.230000e+00
Basic EPS,5.180000e+00,3.730000e+00,3.660000e+00,3.470000e+00,3.240000e+00
Diluted NI Availto Com Stockholders,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10,2.410800e+10
Net Income Common Stockholders,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10,2.410800e+10
Net Income,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10,2.410800e+10
Net Income Including Noncontrolling Interests,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10,2.410800e+10
Net Income Continuous Operations,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10,2.410800e+10
Tax Provision,9.788000e+09,6.554000e+09,5.383000e+09,5.553000e+09,5.257000e+09
Pretax Income,4.824600e+10,3.430100e+10,3.261600e+10,3.137700e+10,2.936500e+10
Other Income Expense,9.867000e+09,-3.938000e+09,-1.861000e+09,-6.260000e+08,-2.294000e+09
Other Non Operating Income Expenses,9.541000e+09,-4.923000e+09,-1.864000e+09,-1.013000e+09,-1.165000e+09
Special Income Charges,-5.900000e+07,-1.400000e+07,-4.500000e+07,-2.400000e+07,-8.670000e+08
Write Off,5.900000e+07,1.400000e+07,4.500000e+07,2.400000e+07,8.670000e+08
Gain On Sale Of Security,3.850000e+08,9.990000e+08,4.800000e+07,4.110000e+08,-2.620000e+08
Net Non Operating Interest Income Expense,1.040000e+08,2.780000e+08,1.540000e+08,3.000000e+06,6.000000e+06
Interest Expense Non Operating,7.360000e+08,6.980000e+08,6.150000e+08,5.940000e+08,5.940000e+08
Interest Income Non Operating,8.400000e+08,9.760000e+08,7.690000e+08,5.970000e+08,6.000000e+08
Operating Income,3.827500e+10,3.796100e+10,3.432300e+10,3.200000e+10,3.165300e+10
Operating Expense,1.702000e+10,1.566900e+10,1.810400e+10,1.614700e+10,1.618000e+10
Research And Development,8.504000e+09,8.146000e+09,8.829000e+09,8.198000e+09,7.917000e+09
Selling General And Administration,8.516000e+09,7.523000e+09,9.275000e+09,7.949000e+09,8.263000e+09
Selling And Marketing Expense,6.584000e+09,5.717000e+09,7.285000e+09,6.212000e+09,6.440000e+09
General And Administrative Expense,1.932000e+09,1.806000e+09,1.990000e+09,1.737000e+09,1.823000e+09
Other Gand A,1.932000e+09,1.806000e+09,1.990000e+09,1.737000e+09,1.823000e+09
Gross Profit,5.529500e+10,5.363000e+10,5.242700e+10,4.814700e+10,4.783300e+10
Cost Of Revenue,2.597800e+10,2.404300e+10,2.401400e+10,2.191900e+10,2.179900e+10
Total Revenue,8.127300e+10,7.767300e+10,7.644100e+10,7.006600e+10,6.963200e+10
Operating Revenue,8.127300e+10,7.767300e+10,7.644100e+10,7.006600e+10,6.963200e+10

In [11]:
microsoft.quarterly_balance_sheet

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30,2024-06-30
Ordinary Shares Number,7.429000e+09,7.433088e+09,7.434159e+09,7.433982e+09,7.435257e+09,NaN,NaN
Share Issued,7.429000e+09,7.433088e+09,7.434159e+09,7.433982e+09,7.435257e+09,NaN,NaN
Net Debt,1.596600e+10,1.435900e+10,1.290900e+10,1.405300e+10,2.748800e+10,NaN,NaN
Total Debt,5.760700e+10,6.055600e+10,6.058800e+10,6.056700e+10,6.222400e+10,NaN,NaN
Tangible Book Value,2.509640e+11,2.223430e+11,2.013660e+11,1.785940e+11,1.581190e+11,NaN,NaN
...,...,...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,8.945600e+10,1.020050e+11,9.455500e+10,7.961200e+10,7.155100e+10,NaN,NaN
Other Short Term Investments,6.516000e+10,7.315600e+10,6.431300e+10,5.078400e+10,5.406900e+10,NaN,NaN
Cash And Cash Equivalents,2.429600e+10,2.884900e+10,3.024200e+10,2.882800e+10,1.748200e+10,NaN,NaN
Cash Equivalents,1.407500e+10,1.748300e+10,1.853100e+10,1.814800e+10,7.835000e+09,NaN,NaN
Cash Financial,1.022100e+10,1.136600e+10,1.171100e+10,1.068000e+10,9.647000e+09,NaN,NaN

In [12]:
microsoft.quarterly_cash_flow

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30,2024-06-30
Free Cash Flow,5.882000e+09,2.566300e+10,2.556800e+10,2.029900e+10,6.487000e+09,NaN,NaN
Repurchase Of Capital Stock,-7.415000e+09,-5.650000e+09,-4.546000e+09,-4.781000e+09,-4.986000e+09,NaN,NaN
Repayment Of Debt,-3.000000e+09,0.000000e+00,0.000000e+00,-2.250000e+09,0.000000e+00,NaN,NaN
Issuance Of Debt,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.447000e+09
Issuance Of Capital Stock,2.590000e+08,6.890000e+08,5.480000e+08,5.460000e+08,2.560000e+08,NaN,NaN
Capital Expenditure,-2.987600e+10,-1.939400e+10,-1.707900e+10,-1.674500e+10,-1.580400e+10,NaN,NaN
End Cash Position,2.429600e+10,2.884900e+10,3.024200e+10,2.882800e+10,1.748200e+10,NaN,NaN
Beginning Cash Position,2.884900e+10,3.024200e+10,2.882800e+10,1.748200e+10,2.084000e+10,NaN,NaN
Effect Of Exchange Rate Changes,1.100000e+07,-9.200000e+07,1.830000e+08,5.200000e+07,-2.940000e+08,NaN,NaN
Changes In Cash,-4.564000e+09,-1.301000e+09,1.231000e+09,1.129400e+10,-3.064000e+09,NaN,NaN
Financing Cash Flow,-1.761700e+10,-1.179900e+10,-1.084400e+10,-1.303600e+10,-1.124300e+10,NaN,NaN
Cash Flow From Continuing Financing Activities,-1.761700e+10,-1.179900e+10,-1.084400e+10,-1.303600e+10,-1.124300e+10,NaN,NaN
Net Other Financing Charges,-6.990000e+08,-6.690000e+08,-6.770000e+08,-3.820000e+08,-3.430000e+08,NaN,NaN
Cash Dividends Paid,-6.762000e+09,-6.169000e+09,-6.169000e+09,-6.169000e+09,-6.170000e+09,NaN,NaN
Common Stock Dividend Paid,-6.762000e+09,-6.169000e+09,-6.169000e+09,-6.169000e+09,-6.170000e+09,NaN,NaN
Net Common Stock Issuance,-7.156000e+09,-4.961000e+09,-3.998000e+09,-4.235000e+09,-4.730000e+09,NaN,NaN
Common Stock Payments,-7.415000e+09,-5.650000e+09,-4.546000e+09,-4.781000e+09,-4.986000e+09,NaN,NaN
Common Stock Issuance,2.590000e+08,6.890000e+08,5.480000e+08,5.460000e+08,2.560000e+08,NaN,NaN
Net Issuance Payments Of Debt,-3.000000e+09,0.000000e+00,0.000000e+00,-2.250000e+09,0.000000e+00,NaN,NaN
Net Short Term Debt Issuance,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN
Short Term Debt Payments,0.000000e+00,NaN,NaN,NaN,0.000000e+00,NaN,NaN
Net Long Term Debt Issuance,-3.000000e+09,0.000000e+00,0.000000e+00,-2.250000e+09,0.000000e+00,NaN,NaN
Long Term Debt Payments,-3.000000e+09,0.000000e+00,0.000000e+00,-2.250000e+09,0.000000e+00,NaN,NaN
Long Term Debt Issuance,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.970000e+08
Investing Cash Flow,-2.270500e+10,-3.455900e+10,-3.057200e+10,-1.271400e+10,-1.411200e+10,NaN,NaN
Cash Flow From Continuing Investing Activities,-2.270500e+10,-3.455900e+10,-3.057200e+10,-1.271400e+10,-1.411200e+10,NaN,NaN
Net Other Investing Changes,-6.370000e+08,-6.209000e+09,2.642000e+09,6.040000e+08,-1.600000e+07,NaN,NaN
Net Investment Purchase And Sale,8.263000e+09,-8.378000e+09,-1.439200e+10,4.408000e+09,3.113000e+09,NaN,NaN
Sale Of Investment,1.810800e+10,9.293000e+09,7.239000e+09,8.882000e+09,5.163000e+09,NaN,NaN
Purchase Of Investment,-9.845000e+09,-1.767100e+10,-2.163100e+10,-4.474000e+09,-2.050000e+09,NaN,NaN
Net Business Purchase And Sale,-4.550000e+08,-5.780000e+08,-1.743000e+09,-9.810000e+08,-1.405000e+09,NaN,NaN
Purchase Of Business,-4.550000e+08,-5.780000e+08,-1.743000e+09,-9.810000e+08,-1.405000e+09,NaN,NaN
Net PPE Purchase And Sale,-2.987600e+10,-1.939400e+10,-1.707900e+10,-1.674500e+10,-1.580400e+10,NaN,NaN
Purchase Of PPE,-2.987600e+10,-1.939400e+10,-1.707900e+10,-1.674500e+10,-1.580400e+10,NaN,NaN
Operating Cash Flow,3.575800e+10,4.505700e+10,4.264700e+10,3.704400e+10,2.229100e+10,NaN,NaN
Cash Flow From Continuing Operating Activities,3.575800e+10,4.505700e+10,4.264700e+10,3.704400e+10,2.229100e+10,NaN,NaN
Change In Working Capital,-9.632000e+09,-2.180000e+08,3.303000e+09,2.042000e+09,-1.155100e+10,NaN,NaN
Change In Other Working Capital,-8.403000e+09,-8.362000e+09,1.940400e+10,2.660000e+08,-9.733000e+09,NaN,NaN
Change In Other Current Liabilities,1.609000e+09,-5.984000e+09,4.079000e+09,2.448000e+09,3.933000e+09,NaN,NaN
Change In Other Current Assets,-6.690000e+08,-1.556000e+09,-3.268000e+09,5.580000e+08,-1.442000e+09,NaN,NaN
Change In Payables And Accrued Expense,1.197000e+09,-6.140000e+08,-6.520000e+08,1.179000e+09,9.580000e+08,NaN,NaN
Change In Payable,1.197000e+09,-6.140000e+08,-6.520000e+08,1.179000e+09,9.580000e+08,NaN,NaN
Change In Account Payable,1.197000e+09,-6.140000e+08,-6.520000e+08,1.179000e+09,9.580000e+08,NaN,NaN
Change In Tax Payable,NaN,NaN,NaN,1.298000e+09,-3.395000e+09,1.016000e+09,-8.060000e+08
Change In Income Tax Payable,NaN,NaN,NaN,1.298000e+09,-3.395000e+09,1.016000e+09,-8.060000e+08
Change In Inventory,7.000000e+07,-1.920000e+08,-8.100000e+07,5.200000e+07,7.110000e+08,NaN,NaN
Change In Receivables,-3.436000e+09,1.649000e+10,-1.617900e+10,-2.461000e+09,-5.978000e+09,NaN,NaN
Changes In Account Receivables,-3.436000e+09,1.649000e+10,-1.617900e+10,-2.461000e+09,-5.978000e+09,NaN,NaN
Stock Based Compensation,3.219000e+09,2.983000e+09,3.073000e+09,2.980000e+09,3.089000e+09,NaN,NaN
Unrealized Gain Loss On Investment Securities,NaN,6.350000e+08,3.600000e+07,-1.350000e+08,-2.500000e+07,-4.120000e+08,NaN
Asset Impairment Charge,NaN,1.400000e+07,4.500000e+07,2.400000e+07,8.670000e+08,7.000000e+06,NaN
Deferred Tax,4.446000e+09,2.491000e+09,-2.221000e+09,-2.244000e+09,-1.158000e+09,NaN,NaN
Deferred Income Tax,4.446000e+09,2.491000e+09,-2.221000e+09,-2.244000e+09,-1.158000e+09,NaN,NaN
Depreciation Amortization Depletion,9.198000e+09,1.306100e+10,1.120300e+10,8.740000e+09,5.667000e+09,NaN,NaN
Depreciation And Amortization,9.198000e+09,1.306100e+10,1.120300e+10,8.740000e+09,5.667000e+09,NaN,NaN
Depreciation,9.198000e+09,1.306100e+10,1.120300e+10,8.740000e+09,5.667000e+09,NaN,NaN
Operating Gains Losses,-9.931000e+09,-1.656000e+09,-2.500000e+07,-1.870000e+08,2.136000e+09,NaN,NaN
Gain Loss On Investment Securities,NaN,-1.656000e+09,-2.500000e+07,-1.870000e+08,1.340000e+08,2.800000e+08,NaN
Net Income From Continuing Operations,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10,2.410800e+10,NaN,NaN

### Get attributes related to corporate information

In [14]:
# microsoft.info is an object of the type dictionary
info = pd.Series(microsoft.info) # Converting into a Pandas Series allows us to access the information referenced by the dictionary's key
print(', '.join(info.keys()))

address1, city, state, zip, country, phone, website, industry, industryKey, industryDisp, sector, sectorKey, sectorDisp, longBusinessSummary, fullTimeEmployees, companyOfficers, auditRisk, boardRisk, compensationRisk, shareHolderRightsRisk, overallRisk, governanceEpochDate, compensationAsOfEpochDate, irWebsite, executiveTeam, maxAge, priceHint, previousClose, open, dayLow, dayHigh, regularMarketPreviousClose, regularMarketOpen, regularMarketDayLow, regularMarketDayHigh, dividendRate, dividendYield, exDividendDate, payoutRatio, fiveYearAvgDividendYield, beta, trailingPE, forwardPE, volume, regularMarketVolume, averageVolume, averageVolume10days, averageDailyVolume10Day, bid, ask, bidSize, askSize, marketCap, fiftyTwoWeekLow, fiftyTwoWeekHigh, allTimeHigh, allTimeLow, priceToSalesTrailing12Months, fiftyDayAverage, twoHundredDayAverage, trailingAnnualDividendRate, trailingAnnualDividendYield, currency, tradeable, enterpriseValue, profitMargins, floatShares, sharesOutstanding, sharesShort, sharesShortPriorMonth, sharesShortPreviousMonthDate, dateShortInterest, sharesPercentSharesOut, heldPercentInsiders, heldPercentInstitutions, shortRatio, shortPercentOfFloat, impliedSharesOutstanding, bookValue, priceToBook, lastFiscalYearEnd, nextFiscalYearEnd, mostRecentQuarter, earningsQuarterlyGrowth, netIncomeToCommon, trailingEps, forwardEps, lastSplitFactor, lastSplitDate, enterpriseToRevenue, enterpriseToEbitda, 52WeekChange, SandP52WeekChange, lastDividendValue, lastDividendDate, quoteType, currentPrice, targetHighPrice, targetLowPrice, targetMeanPrice, targetMedianPrice, recommendationMean, recommendationKey, numberOfAnalystOpinions, totalCash, totalCashPerShare, ebitda, totalDebt, quickRatio, currentRatio, totalRevenue, debtToEquity, revenuePerShare, returnOnAssets, returnOnEquity, grossProfits, freeCashflow, operatingCashflow, earningsGrowth, revenueGrowth, grossMargins, ebitdaMargins, operatingMargins, financialCurrency, symbol, language, region, typeDisp, quoteSourceName, triggerable, customPriceAlertConfidence, marketState, regularMarketPrice, market, esgPopulated, corporateActions, regularMarketTime, exchange, messageBoardId, exchangeTimezoneName, exchangeTimezoneShortName, gmtOffSetMilliseconds, regularMarketChangePercent, epsTrailingTwelveMonths, epsForward, epsCurrentYear, priceEpsCurrentYear, fiftyDayAverageChange, fiftyDayAverageChangePercent, twoHundredDayAverageChange, twoHundredDayAverageChangePercent, sourceInterval, exchangeDataDelayedBy, averageAnalystRating, cryptoTradeable, shortName, longName, hasPrePostMarketData, firstTradeDateMilliseconds, regularMarketChange, regularMarketDayRange, fullExchangeName, averageDailyVolume3Month, fiftyTwoWeekLowChange, fiftyTwoWeekLowChangePercent, fiftyTwoWeekRange, fiftyTwoWeekHighChange, fiftyTwoWeekHighChangePercent, fiftyTwoWeekChangePercent, dividendDate, earningsTimestamp, earningsTimestampStart, earningsTimestampEnd, earningsCallTimestampStart, earningsCallTimestampEnd, isEarningsDateEstimate, displayName, trailingPegRatio

### Microsoft's current share price

In [16]:
info.currentPrice

386.59

### Helper function to collect company's ratios.

In [18]:
def collect_ratios(tickers: list, ratios: list):
    rows = []

    for ticker in tickers:
        info = yf.Ticker(ticker).info
        row = [ticker] + [info.get(ratio, None) for ratio in ratios]
        rows.append(row)

    return pd.DataFrame(rows, columns=["Ticker"] + ratios)

### Collect the current and quick ratios of four companies:
- Walmart (_WMT_)
- Altria (_MO_)
- NVIDIA (_NVDA_)
- Salesforce (_CRM_)

In [19]:
collect_ratios(["WMT", "MO", "NVDA", "CRM"], ["sector", "industry", "currentRatio", "quickRatio"])

  Ticker              sector                industry  currentRatio  quickRatio
0    WMT  Consumer Defensive         Discount Stores         0.790       0.204
1     MO  Consumer Defensive                 Tobacco         0.648       0.489
2   NVDA          Technology          Semiconductors         4.468       3.605
3    CRM          Technology  Software - Application         0.984       0.785